crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tickets.urls', namespace='tickets')),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('finance/', include('finance.urls', namespace='finance')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

tickets/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'tickets'

urlpatterns = [
    # path('login/', views.user_login, name='login'),
    path('', auth_views.LoginView.as_view(), name='login'),
    path('', auth_views.LogoutView.as_view(), name='logout'),
    path('ticket/', views.ticket_list_view, name='ticket_list'),
    path('create/', views.ticket_create_view, name='ticket_create'),
    path('index/', views.index_view, name='index_view'),
    path('tickets/<int:pk>/edit/', views.ticket_update_view, name='ticket_edit'),
    path('tickets/<int:pk>/delete/', views.ticket_delete_view, name='ticket_delete'),
    path('<int:ticket_id>/update_stage/', views.ticket_update_stage, name='ticket_update_stage'),
    path('<int:ticket_id>/update_status/', views.update_ticket_status, name='ticket_update_status'),
]
    

users/urls.py
# from django.contrib.auth import views as auth_views
from django.urls import include, path

from . import views

app_name = "users"

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('login/', views.user_login, name='login'),
    path('clients/', views.list_clients, name='client_list'),
    path('employees/', views.list_employee, name='list_employee'),
    path('employee/create/', views.create_employee, name='create_employee'),

]

users/models.py
from django.contrib.auth.models import User
from django.db import models

# Role Model
class Role(models.Model):
    SYSTEM_USER_CHOICES = [
        ('admin', 'Администратор'),
        ('employee', 'Сотрудник'),
    ]

    position = models.CharField(max_length=100, verbose_name="Должность")
    system_user = models.CharField(
        max_length=50, choices=SYSTEM_USER_CHOICES, verbose_name="Тип системного пользователя"
    )

    class Meta:
        verbose_name = "Роль"
        verbose_name_plural = "Роли"
        indexes = [
            models.Index(fields=["system_user"]),
        ]

    def __str__(self):
        return self.position


# Person Model
class Person(models.Model):
    GENDER_CHOICES = [
        ('male', 'Мужчина'),
        ('female', 'Женщина'),
    ]

    first_name = models.CharField(max_length=50, verbose_name="Имя", db_index=True)
    last_name = models.CharField(max_length=50, verbose_name="Фамилия", db_index=True)
    nickname = models.CharField(max_length=50, null=True, blank=True, verbose_name="Прозвище")
    gender = models.CharField(
        max_length=10, choices=GENDER_CHOICES, null=True, blank=True, verbose_name="Пол"
    )
    phone_number_1 = models.CharField(max_length=20, unique=True, verbose_name="Телефон 1")
    phone_number_2 = models.CharField(max_length=20, null=True, blank=True, verbose_name="Телефон 2")

    class Meta:
        verbose_name = "Личность"
        verbose_name_plural = "Личности"
        indexes = [
            models.Index(fields=["first_name"]),
            models.Index(fields=["last_name"]),
        ]
        constraints = [
            models.UniqueConstraint(fields=['first_name', 'last_name', 'phone_number_1'], name="unique_person")
        ]

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Employee(models.Model):
    person = models.ForeignKey(
        Person, on_delete=models.CASCADE, related_name="employees", verbose_name="Личность"
    )
    role = models.ForeignKey(
        Role, on_delete=models.SET_NULL, null=True, related_name="employees", verbose_name="Роль"
    )
    user = models.OneToOneField(
        User, on_delete=models.SET_NULL, null=True, blank=True, related_name="employee", verbose_name="Пользователь"
    )

    class Meta:
        verbose_name = "Сотрудник"
        verbose_name_plural = "Сотрудники"
        indexes = [
            models.Index(fields=["role"]),
        ]

    def __str__(self):
        return f"{self.person} - {self.role} - {'No User' if not self.user else self.user.username}"

class Client(models.Model):
    CLIENT_TYPE_CHOICES = [
        ('g', 'Г'),
        ('b', 'ЮЛ'),
        ('f', 'ФЛ'),
    ]

    person = models.ForeignKey(
        Person, on_delete=models.CASCADE, related_name="clients", verbose_name="Личность"
    )
    type = models.CharField(
        max_length=1, choices=CLIENT_TYPE_CHOICES, verbose_name="Тип клиента"
    )
    fin_account = models.IntegerField(
        null=True, blank=True, verbose_name="Финансовый аккаунт"
    )  

    class Meta: 
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"
        indexes = [
            models.Index(fields=["type"]),
        ]

    def __str__(self):
        return f"{self.person} ({self.get_type_display()})"


                          

users/forms.py
from django import forms
from .models import Employee


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['person', 'role', 'user']
        widgets = {
            'person': forms.Select(attrs={'class': 'form-control'}),
            'role': forms.Select(attrs={'class': 'form-control'}),
            'user': forms.Select(attrs={'class': 'form-control'}),
        }

users/views.py
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import (
    LoginForm,
    EmployeeForm
)
from .models import Client, Employee


# Create your views here.
def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                request,
                username=cd['username'],
                password=cd['password'],
            )
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'users/login.html', {'form': form})

def list_clients(request):
    clients = Client.objects.all()  # Get all clients
    return render(request, 'users/client_list.html', {'clients': clients, 'section': 'clients'})

def list_employee(request):
    employees = Employee.objects.all()  # Get all clients
    return render(request, 'users/employees_list.html', {'employees': employees, 'section': 'employees'})

def create_employee(request):
    if request.method == 'POST':
        form = EmployeeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:list_employee')  # Redirect to an employee list or another page
    else:
        form = EmployeeForm()
    return render(request, 'users/employee_form.html', {'form': form , 'section': 'employees'})

users/templates/users/client_list.html
{% extends "base.html" %}

{% block main %}
<div class="content">
  <div class="mb-9" data-bs-spy="scroll" data-bs-target="#widgets-scrollspy">
    <div class="d-flex mb-5 pt-8" id="scrollspyStats"><span class="fa-stack me-2 ms-n1"><i class="fas fa-circle fa-stack-2x text-primary"></i><i class="fa-inverse fa-stack-1x text-primary-subtle"></i></span>
      <div class="col">
        <h3 class="mb-0 text-primary position-relative fw-bold"><span class="bg-body pe-2">Список клиентов</span><span class="border border-primary position-absolute top-50 translate-middle-y w-100 start-0 z-n1"></span></h3>
      </div>
    </div>

  <!-- <a href="{% url 'tickets:ticket_create' %}" class="btn btn-success">Добавить клиента</a> -->
  <table class="table">
    <thead>
        <tr>
            <th>Имя</th>
            <th>Фамилия</th>
            <th>Телефон</th>
        </tr>
    </thead>
    <tbody>
        {% for client in clients %}
        <tr>
            <td>{{ client.person.first_name }}</td>
            <td>{{ client.person.last_name }}</td>
            <td>{{ client.person.phone_number_1 }}</td>
        </tr>
        {% endfor %}
    </tbody>
  </table>
  </div>
  </div>
{% endblock %}

    

users/templates/users/employee_form.html
<!-- Template for ticket_form.html -->
{% extends "base.html" %}

{% block main %}
<div class="content">
  <div class="mb-9" data-bs-spy="scroll" data-bs-target="#widgets-scrollspy">
    <div class="d-flex mb-5 pt-8" id="scrollspyStats"><span class="fa-stack me-2 ms-n1"><i class="fas fa-circle fa-stack-2x text-primary"></i><i class="fa-inverse fa-stack-1x text-primary-subtle"></i></span>
      <div class="col">
        <h3 class="mb-0 text-primary position-relative fw-bold"><span class="bg-body pe-2">Добавить сотрудника</span><span class="border border-primary position-absolute top-50 translate-middle-y w-100 start-0 z-n1"></span></h3>
      </div>
    </div>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Добавить сотрудника</button>
  </form>
  <a href="{% url 'tickets:ticket_list' %}" class="btn btn-secondary">Отмена</a>
  </div>
</div>
{% endblock %}

users/templates/users/employees_list.html
{% extends "base.html" %}

{% block main %}
<div class="content">
  <div class="mb-9" data-bs-spy="scroll" data-bs-target="#widgets-scrollspy">
    <div class="d-flex mb-5 pt-8" id="scrollspyStats"><span class="fa-stack me-2 ms-n1"><i class="fas fa-circle fa-stack-2x text-primary"></i><i class="fa-inverse fa-stack-1x text-primary-subtle"></i></span>
      <div class="col">
        <h3 class="mb-0 text-primary position-relative fw-bold"><span class="bg-body pe-2">Список сотрудников</span><span class="border border-primary position-absolute top-50 translate-middle-y w-100 start-0 z-n1"></span></h3>
      </div>
    </div>

  <a href="{% url 'users:create_employee' %}" class="btn btn-success">Добавить сотрудника</a>
  <table class="table">
    <thead>
        <tr>
            <th>Имя</th>
            <th>Фамилия</th>
            <th>Должность</th>
        </tr>
    </thead>
    <tbody>
        {% for employee in employees %}
        <tr>
            <td>{{ employee.person.first_name }}</td>
            <td>{{ employee.person.last_name }}</td>
            <td>{{ employee.role }}</td>
        </tr>
        {% endfor %}
    </tbody>
  </table>
  </div>
  </div>
{% endblock %}

    